# Generated by Django 2.2.6 on 2019-11-02 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='category',
            new_name='department',
        ),
    ]
