# Generated by Django 2.2.6 on 2019-11-02 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20191102_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='department',
        ),
    ]
