# Generated by Django 2.2.6 on 2019-11-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_auto_20191117_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='booked_date',
            field=models.DateField(auto_now=True),
        ),
    ]
