# Generated by Django 2.2.6 on 2019-11-02 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billcategory',
            options={'verbose_name_plural': 'Bill Categories'},
        ),
    ]
