# Generated by Django 2.2.6 on 2019-11-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20191102_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='photo',
            field=models.ImageField(default='123', upload_to='patients/images/'),
            preserve_default=False,
        ),
    ]
