# Generated by Django 2.2.6 on 2019-11-09 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_department_icon'),
        ('patients', '0005_auto_20191109_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.TextField(default='abc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='consulting_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='doctors.Doctor'),
        ),
        migrations.AddField(
            model_name='patient',
            name='diagnosed_case',
            field=models.TextField(default='fever'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(default='9999999999', max_length=10),
            preserve_default=False,
        ),
    ]
