# Generated by Django 2.2.6 on 2019-11-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_auto_20191110_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinstance',
            name='mrd_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
