# Generated by Django 2.2.6 on 2019-11-16 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_auto_20191116_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billdetail',
            name='patient_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.PatientInstance'),
        ),
    ]
