# Generated by Django 2.2.6 on 2019-11-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_auto_20191116_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinstance',
            name='pay_now',
            field=models.BooleanField(default=False),
        ),
    ]
