# Generated by Django 2.2.6 on 2019-11-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_auto_20191102_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='icon',
            field=models.CharField(default='heartbeat', max_length=20),
            preserve_default=False,
        ),
    ]
